site_name: PhysiX-AI Wiki
site_description: A community wiki for learning Physical AI by PhysiX-AI.

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    code: Fira Code
  language: en
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - search.suggest

nav:
  - Home: index.md
  - Quick Start:
    - quick_start/quick_start.md
    - Getting Started with Git: quick_start/git.md
  - About: about.md